# Internal keyword lists for English and French

fungus_keywords_en <- list(
  list(name = "fung",      patterns = c("\\bfungus\\b", "\\bfungi\\b", "\\bfungal\\b", "\\bfungariun\\b")),
  list(name = "lichen",    patterns = c("\\blichens?\\b")),
  list(name = "myc",       patterns = c("myc")),
  list(name = "mould",     patterns = c("\\bmoulds?\\b", "\\bmolds?\\b")),
  list(name = "mushroom",  patterns = c("\\bmushrooms?\\b")),
  list(name = "rust",      patterns = c("\\brusts?\\b")),
  list(name = "smut",      patterns = c("\\bsmuts?\\b")),
  list(name = "toadstool", patterns = c("\\btoadstools?\\b")),
  list(name = "truffle",   patterns = c("\\btruffles?\\b")),
  list(name = "yeast",     patterns = c("\\byeasts?\\b"))
)

animal_keywords_en <- list(
  list(name = "Amphibian",     patterns = c("amphibi")),
  list(name = "Animal",        patterns = c("\\banimal")),
  list(name = "Arthropod",     patterns = c("\\barthropod")),
  list(name = "Bat",           patterns = c("\\bbats?\\b")),
  list(name = "Bear",          patterns = c("\\bbear")),
  list(name = "Bee",           patterns = c("\\bbees?\\b")),
  list(name = "Beetle",        patterns = c("\\bbeetle")),
  list(name = "Bird",          patterns = c("\\bbird")),
  list(name = "Bryozoan",      patterns = c("\\bbryozoan")),
  list(name = "Butterfly",     patterns = c("\\bbutterfly")),
  list(name = "Cattle",        patterns = c("\\bcattle", "\\bbovin")),
  list(name = "Coral",         patterns = c("\\bcoral")),
  list(name = "Crustacean",    patterns = c("\\bcrustacean")),
  list(name = "Dolphin",       patterns = c("\\bdolphin")),
  list(name = "Dragonfly",     patterns = c("\\bdragonfly")),
  list(name = "Duck",          patterns = c("\\bduck")),
  list(name = "Falcon",        patterns = c("\\bfalcon")),
  list(name = "Fauna",         patterns = c("\\bfauna")),
  list(name = "Fish",          patterns = c("\\bfish")),
  list(name = "Frog",          patterns = c("\\bfrog")),
  list(name = "Goose",         patterns = c("\\bgoose")),
  list(name = "Insect",        patterns = c("\\binsects?\\b")),
  list(name = "Lynx",          patterns = c("\\blynx")),
  list(name = "Mammal",        patterns = c("\\bmammal")),
  list(name = "Mollusc",       patterns = c("\\bmollusc")),
  list(name = "Moth",          patterns = c("\\bmoth")),
  list(name = "Owl",           patterns = c("\\bowls?\\b")),
  list(name = "Porpoise",      patterns = c("\\bporpoise")),
  list(name = "Raptor",        patterns = c("\\braptor")),
  list(name = "Reptile",       patterns = c("\\breptile")),
  list(name = "Rodent",        patterns = c("\\brodent")),
  list(name = "Seal",          patterns = c("\\bseal")),
  list(name = "Snail",         patterns = c("\\bsnail")),
  list(name = "Snake",         patterns = c("\\bsnake")),
  list(name = "Tortoise",      patterns = c("\\btortoise")),
  list(name = "Turtle",        patterns = c("\\bturtle")),
  list(name = "(in)vertebrate", patterns = c("\\bvertebrate", "\\binvertebrate")),
  list(name = "Wader",         patterns = c("\\bwader")),
  list(name = "Wasp",          patterns = c("\\bwasp")),
  list(name = "Whale",         patterns = c("\\bwhale")),
  list(name = "Wolf",          patterns = c("\\bwolf")),
  list(name = "Worm",          patterns = c("\\bworm", "\\bhelminthe"))
)

plant_keywords_en <- list(
  list(name = "Bryophyte", patterns = c("\\bbryophyte", "\\bphyte")),
  list(name = "Conifer",   patterns = c("\\bconifer")),
  list(name = "Fern",      patterns = c("\\bferns?\\b")),
  list(name = "Flora",     patterns = c("\\bflora")),
  list(name = "Flower",    patterns = c("\\bflower")),
  list(name = "Moss",      patterns = c("\\bmosses?\\b")),
  list(name = "Plant",     patterns = c("\\bplant", "\\bvegeta")),
  list(name = "Tree",      patterns = c("\\btree"))
)

fungus_keywords_fr <- list(
  list(name = "fung",      patterns = c("\\bfongiques?\\b", "\\bfonge\\b", "\\bfongiers?\\b")),
  list(name = "lichen",    patterns = c("\\blichens?\\b")),
  list(name = "myc",       patterns = c("myc")),
  list(name = "mould",     patterns = c("\\bmoisissures?\\b")),
  list(name = "mushroom",  patterns = c("\\bchampignons?\\b")),
  list(name = "rust",      patterns = c("\\brouilles?\\b")),
  # list(name = "smut",      patterns = c("charbon")),  # removed
  list(name = "toadstool", patterns = c("\\btoadstool")),
  list(name = "truffle",   patterns = c("\\btruffes?\\b")),
  list(name = "yeast",     patterns = c("\\blevures?\\b"))
)

animal_keywords_fr <- list(
  list(name = "Amphibian",     patterns = c("amphibi")),
  list(name = "Animal",        patterns = c("\\banimal")),
  list(name = "Arthropod",     patterns = c("\\barthropod")),
  list(name = "Bat",           patterns = c("\\bchauve-souris")),
  list(name = "Bear",          patterns = c("\\bours\\b")),
  list(name = "Bee",           patterns = c("\\babeille")),
  list(name = "Beetle",        patterns = c("\\bcoléoptère")),
  list(name = "Bird",          patterns = c("\\boiseau")),
  list(name = "Bryozoan",      patterns = c("\\bbryozoaire")),
  list(name = "Butterfly",     patterns = c("\\bpapillon")),
  list(name = "Cattle",        patterns = c("\\bbétail", "\\bbovin", "\\bboeuf")),
  list(name = "Coral",         patterns = c("\\bcorail")),
  list(name = "Crustacean",    patterns = c("\\bcrustacé")),
  list(name = "Dolphin",       patterns = c("\\bdauphin")),
  list(name = "Dragonfly",     patterns = c("\\blibellule")),
  list(name = "Duck",          patterns = c("\\bcanard")),
  list(name = "Falcon",        patterns = c("\\bfaucon")),
  list(name = "Fauna",         patterns = c("\\bfaune", "\\bfaunique", "\\bfaunistique")),
  list(name = "Fish",          patterns = c("\\bpoisson")),
  list(name = "Frog",          patterns = c("\\bgrenouille")),
  list(name = "Goose",         patterns = c("\\boies?\\b")),
  list(name = "Insect",        patterns = c("\\binsectes?\\b")),
  list(name = "Lynx",          patterns = c("\\blynx")),
  list(name = "Mammal",        patterns = c("\\bmammifère")),
  list(name = "Mollusc",       patterns = c("\\bmollusque")),
  # list(name = "Moth",          patterns = c("\\bmite")),
  list(name = "Owl",           patterns = c("\\bhibou")),
  list(name = "Porpoise",      patterns = c("\\bmarsouin")),
  list(name = "Raptor",        patterns = c("\\brapace")),
  list(name = "Reptile",       patterns = c("\\breptile")),
  list(name = "Rodent",        patterns = c("\\brongeur")),
  list(name = "Seal",          patterns = c("\\bphoques?\\b")),
  list(name = "Snail",         patterns = c("\\bescargot")),
  list(name = "Snake",         patterns = c("\\bserpent")),
  # list(name = "Tortoise",      patterns = c("tortue")),
  list(name = "Turtle",        patterns = c("\\btortue")),
  list(name = "(in)vertebrate", patterns = c("\\bvertébré", "\\binvertébré")),
  list(name = "Wader",         patterns = c("\\béchassier")),
  list(name = "Wasp",          patterns = c("\\bguêpe")),
  list(name = "Whale",         patterns = c("\\bbaleine")),
  list(name = "Wolf",          patterns = c("\\bloups?\\b")),
  list(name = "Worm",          patterns = c("\\bver de terre\\b", "\\bvers de terre\\b", "\\bhelminthe"))
)

plant_keywords_fr <- list(
  list(name = "Bryophyte", patterns = c("\\bbryophyte", "\\bphyte")),
  list(name = "Conifer",   patterns = c("\\bconifère")),
  list(name = "Fern",      patterns = c("\\bfougère")),
  list(name = "Flora",     patterns = c("\\bflore")),
  list(name = "Flower",    patterns = c("\\bfleur")),
  list(name = "Moss",      patterns = c("\\bmousse")),
  list(name = "Plant",     patterns = c("\\bplante", "\\bvégéta")),
  list(name = "Tree",      patterns = c("\\barbre"))
)